export const COLORS = {
  BACKGOUND_BLUE: "#000c75",
  BACKGOUND_WHITE: "#fff",
  BACKGOUND_WHITE_BLUE: "#f6fbff",
  COLOR_WHITE: "#fff",
  COLOR_BLUE: "#000c75",
  COLOR_GREAY: "#ccc",
  BTN_BACKGROUND_SKY: "#00c2ff",
  BTN_BACKGROUND_WHITE: "#fff",
  COLOR_DARK: "#35373e",
  COLOR_SKY: "#00c2ff",
};
